/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_menu;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Shape3D;
import javax.media.j3d.TransformGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.vecmath.Matrix4d;

/**
 *
 * @author levan
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    JInternalWorld iWorld;
    BranchGroup current_bg;
    TransformGroup current_g;
    ArrayList <Shape3D> Shapes;
    ArrayList<String> list; 

    //Constructor for Trung's Load Function
    public App(ArrayList<String> list, String file_name){
        this.list= list;
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle(file_name);
        setSize(1366, 768);
        setLocationRelativeTo(null);
        initComponents();
        this.Shapes = new ArrayList <Shape3D>();
        iWorld = new JInternalWorld(true, true, true, Shapes, list);
        iWorld.setSize(DestopPn.getSize());
        iWorld.setLocation(0, 0);
        iWorld.setResizable(true);
        DestopPn.add(iWorld);
        iWorld.setVisible(true);    
    }
    
    
    //Default Constructor for new Project
    public App() {

        //make sure the program exits when the frame closes
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Untitled Project");
        
        
        initComponents();
        setSize(1366, 768);
        setLocationRelativeTo(null);
        this.Shapes = new ArrayList <Shape3D>();
        list = new ArrayList<String>();
        iWorld = new JInternalWorld(true, true, true, Shapes, list);
        iWorld.setSize(DestopPn.getSize());
        iWorld.setLocation(0, 0);
        iWorld.setResizable(true);
        DestopPn.add(iWorld);
        iWorld.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        DestopPn = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        help_menu_item = new javax.swing.JMenuItem();
        about_menu_item = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout DestopPnLayout = new javax.swing.GroupLayout(DestopPn);
        DestopPn.setLayout(DestopPnLayout);
        DestopPnLayout.setHorizontalGroup(
            DestopPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1282, Short.MAX_VALUE)
        );
        DestopPnLayout.setVerticalGroup(
            DestopPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(DestopPn);

        jMenu1.setText("File");

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Load");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Document");

        help_menu_item.setText("Help");
        help_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_menu_itemActionPerformed(evt);
            }
        });
        jMenu2.add(help_menu_item);

        about_menu_item.setText("About us");
        about_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_menu_itemActionPerformed(evt);
            }
        });
        jMenu2.add(about_menu_item);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        // we create an internal world to be added within the JDesktop.
        iWorld = new JInternalWorld(true, true, true, this.Shapes, list);
        iWorld.setSize(DestopPn.getSize());
        iWorld.setLocation(0, 0);
        iWorld.setResizable(true);
        DestopPn.add(iWorld);
        iWorld.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addmenu addmn = new addmenu(this, true);
        addmn.setVisible(true);
        boolean caninput= true;
        if (!addmn.getAction().equals("none")) {
            
            for (Shape3D area: Shapes){
                if (((Area)area).vec.x == addmn.getXX() && ((Area)area).vec.y == addmn.getYY()){
                    caninput = false;
                }
            }
            
            
            Area area = new Area(this.iWorld.getA(), addmn.getXX(), 0.1,
                    addmn.getYY(), addmn.getAction(),this.iWorld.getCanvas(),
                    this.iWorld.getBoundsj3d(),this.iWorld.getObjTrans(),this.Shapes);
                   
            
             for (Shape3D are: Shapes){
                if (((Area)are).getT3d().toString().equals(area.getT3d().toString())){
                    caninput = false;
                }
            }
            
            if (caninput){
            this.iWorld.getObjTrans().addChild(area.getBg());
            this.Shapes.add(area);
            }
            else{
                Error error = new Error(this, true);
                error.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        list = new ArrayList<String>();
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                Scanner s = new Scanner(selectedFile);
                setTitle(selectedFile.getName());
                //Get Building Array
                
                while (s.hasNext()) {
                    String str= s.nextLine();
                    System.out.println(str);
                    list.add(str);
                }
                s.close();
            } catch (IOException ex) {
                Logger.getLogger(main_menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        this.Shapes = new ArrayList <Shape3D>();
        iWorld.setVisible(false);
        iWorld = new JInternalWorld(true, true, true, Shapes, list);
        iWorld.setSize(DestopPn.getSize());
        iWorld.setLocation(0, 0);
        iWorld.setResizable(true);
        DestopPn.add(iWorld);
        iWorld.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:  
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        
        
        ArrayList<String> listw = new ArrayList<String>();
        for (Shape3D shape : this.Shapes){
            Matrix4d matr = null;
           // ((Area)shape).getT3d().get(matr);
            String infor =    ((Area)shape).getT3d().toString().replaceAll("\n", ", ") +
                    ((Area)shape).housename;
            listw.add(infor);
        }
        
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showSaveDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                PrintWriter pw = new PrintWriter(new FileOutputStream(selectedFile));
                
                //Array Building Here----------------- Trung
                for (String club : listw) {
                    pw.println(club);
                }
                pw.close();
            } catch (IOException ex) {
                Logger.getLogger(main_menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void help_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_menu_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_help_menu_itemActionPerformed

    private void about_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_menu_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_about_menu_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new App().setVisible(true);
        });
    }

    //Trung's set Constructor
    public void auto_open_JInternalWorld(int width, int height) {
        // TODO add your handling code here:

        JInternalWorld iWorld;
        // we create an internal world to be added within the JDesktop.
        iWorld = new JInternalWorld(true, true, true, this.Shapes, list); //Problem create new Sphere Group with sizeable ground
        iWorld.setSize(DestopPn.getSize());
        iWorld.setLocation(0, 0);
        iWorld.setResizable(true);

        DestopPn.add(iWorld);
        iWorld.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DestopPn;
    private javax.swing.JMenuItem about_menu_item;
    private javax.swing.JMenuItem help_menu_item;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
